# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 590)
        Form.setStyleSheet("")
        self.container_root = QtWidgets.QWidget(Form)
        self.container_root.setGeometry(QtCore.QRect(20, 20, 800, 550))
        self.container_root.setStyleSheet("QWidget #container_root{\n"
"    background-color: rgb(2, 62, 138);\n"
"    border: 0.5px solid;\n"
"    border-radius:20px;\n"
"    border-color: rgb(173, 232, 244)\n"
"}\n"
"\n"
"QLabel{\n"
"    font: \"Gill Sans MT\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color:  rgba(202, 240, 248, 200);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 5px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"    width:15px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.container_root.setObjectName("container_root")
        self.container_widget = QtWidgets.QWidget(self.container_root)
        self.container_widget.setGeometry(QtCore.QRect(10, 40, 780, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container_widget.sizePolicy().hasHeightForWidth())
        self.container_widget.setSizePolicy(sizePolicy)
        self.container_widget.setObjectName("container_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.container_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.container_input = QtWidgets.QWidget(self.container_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.container_input.sizePolicy().hasHeightForWidth())
        self.container_input.setSizePolicy(sizePolicy)
        self.container_input.setStyleSheet("QGroupBox{\n"
"    background-color: rgba(72, 202, 228, 150);\n"
"    border: 0px solid;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QSpinBox {\n"
"    border: none;\n"
"    background:  rgba(202, 240, 248, 200);\n"
"    border-radius:5px;\n"
"    font: 10pt \"Gill Sans MT\";\n"
"}\n"
"\n"
"QSpinBox::up-button{\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    border-radius: 2px;\n"
"    border-image: url(:/icons/icons/chevron-up.svg);\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover{\n"
"    background-color:  rgba(0, 119, 182, 200)\n"
"}\n"
"\n"
"QSpinBox::down-button{\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    border-radius: 2px;\n"
"    border-image: url(:/icons/icons/chevron-down.svg);\n"
"    border-width: 1px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover{\n"
"    background-color:  rgba(0, 119, 182, 200)\n"
"}")
        self.container_input.setObjectName("container_input")
        self.group_one = QtWidgets.QGroupBox(self.container_input)
        self.group_one.setGeometry(QtCore.QRect(10, 10, 359, 60))
        self.group_one.setStyleSheet("")
        self.group_one.setTitle("")
        self.group_one.setObjectName("group_one")
        self.label_stage_one = QtWidgets.QLabel(self.group_one)
        self.label_stage_one.setGeometry(QtCore.QRect(10, 0, 150, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_stage_one.setFont(font)
        self.label_stage_one.setObjectName("label_stage_one")
        self.button_choose_files = QtWidgets.QPushButton(self.group_one)
        self.button_choose_files.setGeometry(QtCore.QRect(280, 8, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_choose_files.sizePolicy().hasHeightForWidth())
        self.button_choose_files.setSizePolicy(sizePolicy)
        self.button_choose_files.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_choose_files.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/image.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_choose_files.setIcon(icon)
        self.button_choose_files.setIconSize(QtCore.QSize(30, 30))
        self.button_choose_files.setObjectName("button_choose_files")
        self.label_no_files = QtWidgets.QLabel(self.group_one)
        self.label_no_files.setGeometry(QtCore.QRect(190, 0, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_no_files.setFont(font)
        self.label_no_files.setStyleSheet("font: 10pt \"Gill Sans MT\";")
        self.label_no_files.setObjectName("label_no_files")
        self.group_two = QtWidgets.QGroupBox(self.container_input)
        self.group_two.setGeometry(QtCore.QRect(10, 85, 359, 112))
        self.group_two.setStyleSheet("")
        self.group_two.setTitle("")
        self.group_two.setObjectName("group_two")
        self.label_stage_two = QtWidgets.QLabel(self.group_two)
        self.label_stage_two.setGeometry(QtCore.QRect(10, 0, 150, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_stage_two.setFont(font)
        self.label_stage_two.setObjectName("label_stage_two")
        self.button_clockwise = QtWidgets.QPushButton(self.group_two)
        self.button_clockwise.setGeometry(QtCore.QRect(220, 8, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clockwise.sizePolicy().hasHeightForWidth())
        self.button_clockwise.setSizePolicy(sizePolicy)
        self.button_clockwise.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_clockwise.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/rotate-cw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_clockwise.setIcon(icon1)
        self.button_clockwise.setIconSize(QtCore.QSize(30, 30))
        self.button_clockwise.setObjectName("button_clockwise")
        self.button_counter_clockwise = QtWidgets.QPushButton(self.group_two)
        self.button_counter_clockwise.setGeometry(QtCore.QRect(280, 8, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_counter_clockwise.sizePolicy().hasHeightForWidth())
        self.button_counter_clockwise.setSizePolicy(sizePolicy)
        self.button_counter_clockwise.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_counter_clockwise.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/rotate-ccw.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_counter_clockwise.setIcon(icon2)
        self.button_counter_clockwise.setIconSize(QtCore.QSize(30, 30))
        self.button_counter_clockwise.setObjectName("button_counter_clockwise")
        self.button_ninety = QtWidgets.QPushButton(self.group_two)
        self.button_ninety.setGeometry(QtCore.QRect(100, 60, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_ninety.sizePolicy().hasHeightForWidth())
        self.button_ninety.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.button_ninety.setFont(font)
        self.button_ninety.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_ninety.setIconSize(QtCore.QSize(30, 30))
        self.button_ninety.setObjectName("button_ninety")
        self.button_one_eighty = QtWidgets.QPushButton(self.group_two)
        self.button_one_eighty.setGeometry(QtCore.QRect(160, 60, 49, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_one_eighty.sizePolicy().hasHeightForWidth())
        self.button_one_eighty.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.button_one_eighty.setFont(font)
        self.button_one_eighty.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_one_eighty.setIconSize(QtCore.QSize(30, 30))
        self.button_one_eighty.setObjectName("button_one_eighty")
        self.angle = QtWidgets.QSpinBox(self.group_two)
        self.angle.setGeometry(QtCore.QRect(280, 70, 48, 24))
        self.angle.setStyleSheet("")
        self.angle.setMaximum(360)
        self.angle.setObjectName("angle")
        self.button_custom_rotation = QtWidgets.QPushButton(self.group_two)
        self.button_custom_rotation.setGeometry(QtCore.QRect(220, 60, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_custom_rotation.sizePolicy().hasHeightForWidth())
        self.button_custom_rotation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.button_custom_rotation.setFont(font)
        self.button_custom_rotation.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_custom_rotation.setIconSize(QtCore.QSize(30, 30))
        self.button_custom_rotation.setObjectName("button_custom_rotation")
        self.group_three = QtWidgets.QGroupBox(self.container_input)
        self.group_three.setGeometry(QtCore.QRect(10, 212, 359, 60))
        self.group_three.setStyleSheet("")
        self.group_three.setTitle("")
        self.group_three.setObjectName("group_three")
        self.label_stage_three = QtWidgets.QLabel(self.group_three)
        self.label_stage_three.setGeometry(QtCore.QRect(10, 0, 150, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_stage_three.setFont(font)
        self.label_stage_three.setObjectName("label_stage_three")
        self.button_different_quality = QtWidgets.QPushButton(self.group_three)
        self.button_different_quality.setGeometry(QtCore.QRect(220, 8, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_different_quality.sizePolicy().hasHeightForWidth())
        self.button_different_quality.setSizePolicy(sizePolicy)
        self.button_different_quality.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_different_quality.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/compression.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_different_quality.setIcon(icon3)
        self.button_different_quality.setIconSize(QtCore.QSize(40, 40))
        self.button_different_quality.setObjectName("button_different_quality")
        self.percentage_quality = QtWidgets.QSpinBox(self.group_three)
        self.percentage_quality.setGeometry(QtCore.QRect(280, 18, 48, 24))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.percentage_quality.setFont(font)
        self.percentage_quality.setStyleSheet("font: 10pt \"Gill Sans MT\";")
        self.percentage_quality.setMinimum(10)
        self.percentage_quality.setMaximum(100)
        self.percentage_quality.setProperty("value", 75)
        self.percentage_quality.setObjectName("percentage_quality")
        self.button_same_quality = QtWidgets.QPushButton(self.group_three)
        self.button_same_quality.setGeometry(QtCore.QRect(160, 8, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_same_quality.sizePolicy().hasHeightForWidth())
        self.button_same_quality.setSizePolicy(sizePolicy)
        self.button_same_quality.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_same_quality.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/file.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_same_quality.setIcon(icon4)
        self.button_same_quality.setIconSize(QtCore.QSize(30, 30))
        self.button_same_quality.setObjectName("button_same_quality")
        self.group_four = QtWidgets.QGroupBox(self.container_input)
        self.group_four.setGeometry(QtCore.QRect(10, 287, 359, 70))
        self.group_four.setStyleSheet("")
        self.group_four.setTitle("")
        self.group_four.setObjectName("group_four")
        self.label_stage_four = QtWidgets.QLabel(self.group_four)
        self.label_stage_four.setGeometry(QtCore.QRect(10, 0, 150, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_stage_four.setFont(font)
        self.label_stage_four.setObjectName("label_stage_four")
        self.choose_colour = QtWidgets.QComboBox(self.group_four)
        self.choose_colour.setGeometry(QtCore.QRect(198, 10, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.choose_colour.setFont(font)
        self.choose_colour.setObjectName("choose_colour")
        self.choose_file_type = QtWidgets.QComboBox(self.group_four)
        self.choose_file_type.setGeometry(QtCore.QRect(197, 40, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(10)
        self.choose_file_type.setFont(font)
        self.choose_file_type.setObjectName("choose_file_type")
        self.group_five = QtWidgets.QGroupBox(self.container_input)
        self.group_five.setGeometry(QtCore.QRect(10, 372, 359, 61))
        self.group_five.setStyleSheet("")
        self.group_five.setTitle("")
        self.group_five.setObjectName("group_five")
        self.label_stage_five = QtWidgets.QLabel(self.group_five)
        self.label_stage_five.setGeometry(QtCore.QRect(10, 0, 150, 60))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_stage_five.setFont(font)
        self.label_stage_five.setObjectName("label_stage_five")
        self.button_choose_save = QtWidgets.QPushButton(self.group_five)
        self.button_choose_save.setGeometry(QtCore.QRect(280, 8, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_choose_save.sizePolicy().hasHeightForWidth())
        self.button_choose_save.setSizePolicy(sizePolicy)
        self.button_choose_save.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_choose_save.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_choose_save.setIcon(icon5)
        self.button_choose_save.setIconSize(QtCore.QSize(30, 30))
        self.button_choose_save.setObjectName("button_choose_save")
        self.horizontalLayout.addWidget(self.container_input)
        self.container_preview = QtWidgets.QWidget(self.container_widget)
        self.container_preview.setObjectName("container_preview")
        self.image_after = QtWidgets.QLabel(self.container_preview)
        self.image_after.setGeometry(QtCore.QRect(10, 85, 360, 360))
        self.image_after.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.image_after.setStyleSheet("font: 28pt \"MS Shell Dlg 2\";")
        self.image_after.setText("")
        self.image_after.setAlignment(QtCore.Qt.AlignCenter)
        self.image_after.setObjectName("image_after")
        self.choose_image = QtWidgets.QComboBox(self.container_preview)
        self.choose_image.setGeometry(QtCore.QRect(10, 45, 361, 30))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.choose_image.setFont(font)
        self.choose_image.setStyleSheet("font: 12pt \"Gill Sans MT\";")
        self.choose_image.setObjectName("choose_image")
        self.label_preview = QtWidgets.QLabel(self.container_preview)
        self.label_preview.setGeometry(QtCore.QRect(10, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_preview.setFont(font)
        self.label_preview.setObjectName("label_preview")
        self.horizontalLayout.addWidget(self.container_preview)
        self.button_start = QtWidgets.QPushButton(self.container_root)
        self.button_start.setGeometry(QtCore.QRect(330, 495, 48, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_start.sizePolicy().hasHeightForWidth())
        self.button_start.setSizePolicy(sizePolicy)
        self.button_start.setToolTipDuration(-1)
        self.button_start.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_start.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/arrow-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_start.setIcon(icon6)
        self.button_start.setIconSize(QtCore.QSize(30, 30))
        self.button_start.setObjectName("button_start")
        self.label_creator = QtWidgets.QLabel(self.container_root)
        self.label_creator.setGeometry(QtCore.QRect(650, 525, 141, 20))
        self.label_creator.setStyleSheet("font: 8pt \"Gill Sans MT\";")
        self.label_creator.setObjectName("label_creator")
        self.nav_bar_widget = QtWidgets.QWidget(self.container_root)
        self.nav_bar_widget.setGeometry(QtCore.QRect(0, 0, 800, 45))
        self.nav_bar_widget.setStyleSheet("QWidget #nav_bar_widget{\n"
"    /*background-color: rgb(3, 4, 94);*/\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.876147 rgba(3, 4, 94, 255), stop:1 rgba(2, 62, 138, 255));\n"
"    border-top: 0.5px solid;\n"
"    border-left: 0.5px solid;\n"
"    border-right: 0.5px solid;\n"
"    border-top-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-color: rgb(173, 232, 244)\n"
"}")
        self.nav_bar_widget.setObjectName("nav_bar_widget")
        self.label_title = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_title.setGeometry(QtCore.QRect(60, 0, 360, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("font: 22pt \"Gill Sans MT\"")
        self.label_title.setObjectName("label_title")
        self.label_icon = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_icon.setGeometry(QtCore.QRect(20, 5, 34, 30))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_icon.setFont(font)
        self.label_icon.setStyleSheet("color: rgb(255,255,255);")
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap(":/icons/new_icon.ico"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setObjectName("label_icon")
        self.button_close = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_close.setGeometry(QtCore.QRect(760, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_close.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon7)
        self.button_close.setIconSize(QtCore.QSize(30, 30))
        self.button_close.setObjectName("button_close")
        self.button_minimise = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_minimise.setGeometry(QtCore.QRect(725, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_minimise.sizePolicy().hasHeightForWidth())
        self.button_minimise.setSizePolicy(sizePolicy)
        self.button_minimise.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_minimise.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimise.setIcon(icon8)
        self.button_minimise.setIconSize(QtCore.QSize(30, 30))
        self.button_minimise.setObjectName("button_minimise")
        self.button_user_guide = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_user_guide.setGeometry(QtCore.QRect(690, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_user_guide.sizePolicy().hasHeightForWidth())
        self.button_user_guide.setSizePolicy(sizePolicy)
        self.button_user_guide.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_user_guide.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_user_guide.setIcon(icon9)
        self.button_user_guide.setIconSize(QtCore.QSize(20, 20))
        self.button_user_guide.setObjectName("button_user_guide")
        self.nav_bar_widget.raise_()
        self.container_widget.raise_()
        self.button_start.raise_()
        self.label_creator.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_stage_one.setText(_translate("Form", "1 - Images"))
        self.button_choose_files.setToolTip(_translate("Form", "Select Files"))
        self.label_no_files.setText(_translate("Form", "0 files chosen"))
        self.label_stage_two.setText(_translate("Form", "2 - Rotation"))
        self.button_clockwise.setToolTip(_translate("Form", "Clockwise Rotation"))
        self.button_counter_clockwise.setToolTip(_translate("Form", "Counter-Clockwise Rotation"))
        self.button_ninety.setToolTip(_translate("Form", "90° Rotation"))
        self.button_ninety.setText(_translate("Form", "90°"))
        self.button_one_eighty.setToolTip(_translate("Form", "180° Rotation"))
        self.button_one_eighty.setText(_translate("Form", "180°"))
        self.angle.setSuffix(_translate("Form", "°"))
        self.button_custom_rotation.setToolTip(_translate("Form", "Custom Rotation"))
        self.button_custom_rotation.setText(_translate("Form", "?°"))
        self.label_stage_three.setText(_translate("Form", "3 - Quality"))
        self.button_different_quality.setToolTip(_translate("Form", "Compress"))
        self.percentage_quality.setSuffix(_translate("Form", "%"))
        self.button_same_quality.setToolTip(_translate("Form", "Same Quality"))
        self.label_stage_four.setText(_translate("Form", "4 - Alterations"))
        self.choose_file_type.setToolTip(_translate("Form", "Destination File Type"))
        self.label_stage_five.setText(_translate("Form", "5 - Destination"))
        self.button_choose_save.setToolTip(_translate("Form", "Select Destination Location"))
        self.label_preview.setText(_translate("Form", "Preview"))
        self.button_start.setToolTip(_translate("Form", "Start"))
        self.label_creator.setText(_translate("Form", "Created by: Nicholas Williams"))
        self.label_title.setText(_translate("Form", "<strong> Image Rotator </strong>"))
        self.button_close.setToolTip(_translate("Form", "Close Application"))
        self.button_minimise.setToolTip(_translate("Form", "Minimise Application"))
        self.button_user_guide.setToolTip(_translate("Form", "Open User Guide"))
import reasources_rc
