# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_guide_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 590)
        self.container_root = QtWidgets.QWidget(Form)
        self.container_root.setGeometry(QtCore.QRect(20, 20, 800, 550))
        self.container_root.setStyleSheet("QWidget #container_root{\n"
"    background-color: rgb(2, 62, 138);\n"
"    border: 0.5px solid;\n"
"    border-radius:20px;\n"
"    border-color: rgb(173, 232, 244)\n"
"}\n"
"\n"
"QLabel{\n"
"    font: \"Gill Sans MT\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color:  rgba(202, 240, 248, 200);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 5px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"    width:15px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.container_root.setObjectName("container_root")
        self.nav_bar_widget = QtWidgets.QWidget(self.container_root)
        self.nav_bar_widget.setGeometry(QtCore.QRect(0, 0, 800, 45))
        self.nav_bar_widget.setStyleSheet("QWidget #nav_bar_widget{\n"
"    /*background-color: rgb(3, 4, 94);*/\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.876147 rgba(3, 4, 94, 255), stop:1 rgba(2, 62, 138, 255));\n"
"    border-top: 0.5px solid;\n"
"    border-left: 0.5px solid;\n"
"    border-right: 0.5px solid;\n"
"    border-top-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-color: rgb(173, 232, 244)\n"
"}")
        self.nav_bar_widget.setObjectName("nav_bar_widget")
        self.label_title = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_title.setGeometry(QtCore.QRect(60, 0, 360, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("font: 22pt \"Gill Sans MT\"")
        self.label_title.setObjectName("label_title")
        self.label_icon = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_icon.setGeometry(QtCore.QRect(20, 5, 34, 30))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_icon.setFont(font)
        self.label_icon.setStyleSheet("color: rgb(255,255,255);")
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap(":/icons/new_icon.ico"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setObjectName("label_icon")
        self.button_close = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_close.setGeometry(QtCore.QRect(760, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon)
        self.button_close.setIconSize(QtCore.QSize(30, 30))
        self.button_close.setObjectName("button_close")
        self.button_minimise = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_minimise.setGeometry(QtCore.QRect(725, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_minimise.sizePolicy().hasHeightForWidth())
        self.button_minimise.setSizePolicy(sizePolicy)
        self.button_minimise.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_minimise.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimise.setIcon(icon1)
        self.button_minimise.setIconSize(QtCore.QSize(30, 30))
        self.button_minimise.setObjectName("button_minimise")
        self.button_user_guide = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_user_guide.setGeometry(QtCore.QRect(690, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_user_guide.sizePolicy().hasHeightForWidth())
        self.button_user_guide.setSizePolicy(sizePolicy)
        self.button_user_guide.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_user_guide.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_user_guide.setIcon(icon2)
        self.button_user_guide.setIconSize(QtCore.QSize(20, 20))
        self.button_user_guide.setObjectName("button_user_guide")
        self.container_content = QtWidgets.QWidget(self.container_root)
        self.container_content.setGeometry(QtCore.QRect(10, 50, 780, 490))
        self.container_content.setObjectName("container_content")
        self.label_page_title = QtWidgets.QLabel(self.container_content)
        self.label_page_title.setGeometry(QtCore.QRect(5, 5, 110, 25))
        self.label_page_title.setStyleSheet("font: 16pt \"Gill Sans MT\";")
        self.label_page_title.setObjectName("label_page_title")
        self.button_back = QtWidgets.QPushButton(self.container_content)
        self.button_back.setGeometry(QtCore.QRect(730, 10, 40, 40))
        self.button_back.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/corner-left-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back.setIcon(icon3)
        self.button_back.setIconSize(QtCore.QSize(30, 30))
        self.button_back.setObjectName("button_back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "<strong> Image Rotator </strong>"))
        self.button_close.setToolTip(_translate("Form", "Close Application"))
        self.button_minimise.setToolTip(_translate("Form", "Minimise Application"))
        self.button_user_guide.setToolTip(_translate("Form", "Open User Guide"))
        self.label_page_title.setText(_translate("Form", "User Guide"))
        self.button_back.setToolTip(_translate("Form", "Back"))
import reasources_rc
