# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_guide_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(840, 590)
        self.container_root = QtWidgets.QWidget(Form)
        self.container_root.setGeometry(QtCore.QRect(20, 20, 800, 550))
        self.container_root.setStyleSheet("QWidget #container_root{\n"
"    background-color: rgb(2, 62, 138);\n"
"    border: 0.5px solid;\n"
"    border-radius:20px;\n"
"    border-color: rgb(173, 232, 244)\n"
"}\n"
"\n"
"QLabel{\n"
"    font: \"Gill Sans MT\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    background-color:  rgba(202, 240, 248, 200);\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 5px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 5px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/icons/icons/chevron-down.svg);\n"
"    width:15px;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.container_root.setObjectName("container_root")
        self.nav_bar_widget = QtWidgets.QWidget(self.container_root)
        self.nav_bar_widget.setGeometry(QtCore.QRect(0, 0, 800, 45))
        self.nav_bar_widget.setStyleSheet("QWidget #nav_bar_widget{\n"
"    /*background-color: rgb(3, 4, 94);*/\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.876147 rgba(3, 4, 94, 255), stop:1 rgba(2, 62, 138, 255));\n"
"    border-top: 0.5px solid;\n"
"    border-left: 0.5px solid;\n"
"    border-right: 0.5px solid;\n"
"    border-top-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    border-color: rgb(173, 232, 244)\n"
"}")
        self.nav_bar_widget.setObjectName("nav_bar_widget")
        self.label_title = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_title.setGeometry(QtCore.QRect(60, 0, 360, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("font: 22pt \"Gill Sans MT\"")
        self.label_title.setObjectName("label_title")
        self.label_icon = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_icon.setGeometry(QtCore.QRect(20, 5, 34, 30))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        self.label_icon.setFont(font)
        self.label_icon.setStyleSheet("color: rgb(255,255,255);")
        self.label_icon.setText("")
        self.label_icon.setPixmap(QtGui.QPixmap(":/icons/new_icon.ico"))
        self.label_icon.setScaledContents(True)
        self.label_icon.setObjectName("label_icon")
        self.button_close = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_close.setGeometry(QtCore.QRect(760, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_close.sizePolicy().hasHeightForWidth())
        self.button_close.setSizePolicy(sizePolicy)
        self.button_close.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon)
        self.button_close.setIconSize(QtCore.QSize(30, 30))
        self.button_close.setObjectName("button_close")
        self.button_minimise = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_minimise.setGeometry(QtCore.QRect(725, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_minimise.sizePolicy().hasHeightForWidth())
        self.button_minimise.setSizePolicy(sizePolicy)
        self.button_minimise.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_minimise.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimise.setIcon(icon1)
        self.button_minimise.setIconSize(QtCore.QSize(30, 30))
        self.button_minimise.setObjectName("button_minimise")
        self.button_user_guide = QtWidgets.QPushButton(self.nav_bar_widget)
        self.button_user_guide.setGeometry(QtCore.QRect(690, 5, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_user_guide.sizePolicy().hasHeightForWidth())
        self.button_user_guide.setSizePolicy(sizePolicy)
        self.button_user_guide.setStyleSheet("QPushButton{\n"
"    background-color: rgba(202, 240, 248, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 119, 182, 200);\n"
"    border: 0px solid;\n"
"    border-radius: 10px;\n"
"    padding:7px;    \n"
"}")
        self.button_user_guide.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_user_guide.setIcon(icon2)
        self.button_user_guide.setIconSize(QtCore.QSize(20, 20))
        self.button_user_guide.setObjectName("button_user_guide")
        self.label_page_title = QtWidgets.QLabel(self.nav_bar_widget)
        self.label_page_title.setGeometry(QtCore.QRect(270, 10, 121, 25))
        self.label_page_title.setStyleSheet("font: 16pt \"Gill Sans MT\";")
        self.label_page_title.setObjectName("label_page_title")
        self.container_content = QtWidgets.QWidget(self.container_root)
        self.container_content.setGeometry(QtCore.QRect(10, 50, 780, 490))
        self.container_content.setObjectName("container_content")
        self.button_back = QtWidgets.QPushButton(self.container_content)
        self.button_back.setGeometry(QtCore.QRect(730, 10, 40, 40))
        self.button_back.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/corner-left-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_back.setIcon(icon3)
        self.button_back.setIconSize(QtCore.QSize(30, 30))
        self.button_back.setObjectName("button_back")
        self.guide_text_left = QtWidgets.QTextBrowser(self.container_content)
        self.guide_text_left.setGeometry(QtCore.QRect(10, 0, 361, 491))
        self.guide_text_left.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 10pt \"Gill Sans MT\";\n"
"border: 0px;")
        self.guide_text_left.setObjectName("guide_text_left")
        self.guide_text_right = QtWidgets.QTextBrowser(self.container_content)
        self.guide_text_right.setGeometry(QtCore.QRect(410, 60, 341, 421))
        self.guide_text_right.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"font: 10pt \"Gill Sans MT\";\n"
"color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.guide_text_right.setObjectName("guide_text_right")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "<strong> Image Rotator </strong>"))
        self.button_close.setToolTip(_translate("Form", "Close Application"))
        self.button_minimise.setToolTip(_translate("Form", "Minimise Application"))
        self.button_user_guide.setToolTip(_translate("Form", "Open User Guide"))
        self.label_page_title.setText(_translate("Form", "- User Guide"))
        self.button_back.setToolTip(_translate("Form", "Back"))
        self.guide_text_left.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gill Sans MT\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Rotating Images</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Stage One - Selecting Image Files</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">In this stage you get to choose the images to rotate. When you press the image button a file explorer window will open allowing any number of image files to be selected. The images have to be in the same folder.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Stage Two - Choosing Image Rotation</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">In this stage you get to choose by how much the image should be rotated by. You are first asked to choose between clockwise and conter-clockwise rotation and then the angle of rotation. There are two preset angles: 90° and 180°. To choose a different angle, select the ?° button and input the angle.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Stage Three - Choosing Image Compression</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">In this stage you get to choose to add image compression. There are two buttons: no-compression and compression. If you select compression, an additional value appears allowing you to specify by how much to compress the image(s).</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Stage Four - Choosing Image Alterations</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">In this stage you get to choose additional alterations to the image. These alterations include converting between colour and black &amp; white as well as the resultant filetype. By default neither will be changed from the original. </span></p></body></html>"))
        self.guide_text_right.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gill Sans MT\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Stage Five - Choosing Image Saving Location</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">In this stage you have to select the location you wish the new images to be saved in. Pressing the folder button will allow you to select a destination location. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; color:#ffffff;\">Starting Rotation Execution</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Once all of the settings have been selected (Stage 1-5) a button should appear below stage 5. This buttons has a right arrow symbol. When pressed, the application will rotate all the images and save them in the specified location.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">General Information</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Buttons in this application are light blue squares with rounded edges. Hovering over a button will provide more information on what it does. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Once you have completed stage one of the process, a preview will appear on the right hand side. Here you can select any of the images and preview how it will look after the execution of the application. </span></p></body></html>"))
import reasources_rc
